---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-test-nr
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/jessieziyuantang/flux-test-nr
