apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-bundle 
  namespace: newrelic
spec:
  chart:
    spec:
      chart: nri-bundle
      sourceRef:
        kind: HelmRepository
        name: newrelic
        namespace: newrelic
      interval: 10m    
  values:
    global:
      cluster: "flux-win-eks"
      licenseKey: cd9571bdbcf2dc60bf4db62fe8f0b53ffc50NRAL
    kube-state-metrics:
      enabled: true   
      image:
        repository: kube-state-metrics/kube-state-metrics
        tag: "2.13.2"
        pullPolicy: IfNotPresent
    newrelic-infrastructure:
      enableLinux: true  # Set to true if your cluster also has linux nodes
      enableWindows: true
      images:
        repository: newrelic/infrastructure-bundle
        tag: "2.7.2"
        pullPolicy: IfNotPresent
      windowsOsList:
        - version: 2022
          imageTag: 2-windows-ltsc2022-alpha
          buildNumber: 10.0.20348
    nri-metadata-injection:
      enabled: false  
    newrelic-logging:
      enabled: false   
    nri-kube-events:
      enabled: false
    newrelic-prometheus-agent:
      enabled: false



      