apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-infrastructure
  namespace: newrelic
spec:
  chart:
    spec:
      chart: newrelic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: newrelic-infrastructure
      interval: 1m0s
  values:
    global:
      cluster: "flux-win-eks"
      licenseKey: cd957*************53ffc50NRAL    