apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-bundle 
  namespace: newrelic
spec:
  interval: 5m
  chart:
    spec:
      chart: nri-bundle
      sourceRef:
        kind: HelmRepository
        name: newrelic
        namespace: newrelic
      interval: 1m    
  values:
    global:
      cluster: "flux-test-nr"
      licenseKey: 
    newrelic-logging:
      enabled: true   
      lowDataMode: true
    newrelic-infrastructure:
      privileged: true
    kube-state-metrics:
      enabled: true   
    nri-kube-events:
      enabled: true
    nri-metadata-injection:
      enabled: true
    nri-prometheus:
      enabled: false



      

