apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-bundle 
  namespace: newrelic
spec:
  interval: 5m
  chart:
    spec:
      chart: nri-bundle
      sourceRef:
        kind: HelmRepository
        name: newrelic
        namespace: newrelic
      interval: 1m    
  values:
    global:
      cluster: "flux-test-nr"
      licenseKey: cd9571bdbcf2dc60bf4db62fe8f0b53ffc50NRAL
    newrelic-logging:
      enabled: true   
      lowDataMode: true
    newrelic-infrastructure:
      privileged: true
    kube-state-metrics:
      enabled: true  
    kubeEvents:
      enabled: true  
    kube-state-metrics:
      

