apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-bundle 
  namespace: newrelic
spec:
   chart:
    spec:
      chart: nri-bundle
      sourceRef:
        kind: HelmRepository
        name: newrelic
        namespace: newrelic
  values:
    global:
      cluster: "flux-test-nr"
  interval: 1m
  install:
    remediation:
      retries: 3
      