apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-bundle 
spec:
   chart:
    spec:
      chart: nri-bundle
      sourceRef:
        kind: HelmRepository
        name: newrelic
  values:
    global:
      cluster: "flux-test-nr"
      licenseKey: cd9571bdbcf2dc60bf4db62fe8f0b53ffc50NRAL
  interval: 1m
  install:
    remediation:
      retries: 3
      