apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-bundle 
  namespace: newrelic
spec:
  interval: 5m
  chart:
    spec:
      chart: nri-bundle
      sourceRef:
        kind: HelmRepository
        name: newrelic
        namespace: newrelic
      interval: 5m    
  values:
    global:
      cluster: "flux-test-nr"
      licenseKey: cd9571bdbcf2dc60bf4db62fe8f0b53ffc50NRAL
    newrelic-logging:
      enabled: true   
      image:
        repository: newrelic/newrelic-fluentbit-output
        tag: "1.16.0"
        pullPolicy: IfNotPresent   
      fluentBit:
        logLevel: "info"
        path: "/var/log/containers/*.log"
        db: "/var/log/flb_kube.db"
        criEnabled: false
        k8sBufferSize: "32k"
        k8sLoggingExclude: "On"
        fluent-bit.conf: |
          [SERVICE]
              Flush         1
              Log_Level     ${LOG_LEVEL}
              Daemon        off
              Parsers_File  parsers.conf
              HTTP_Server   On
              HTTP_Listen   0.0.0.0
              HTTP_Port     2020

          @INCLUDE input-kubernetes.conf
          @INCLUDE output-newrelic.conf
          @INCLUDE filter-kubernetes.conf

        input-kubernetes.conf: |
          [INPUT]
              Name              tail
              Tag               kube.*
              Path              ${PATH}
              Parser            ${LOG_PARSER}
              DB                /var/log/flb_kube.db
              Mem_Buf_Limit     7MB
              Skip_Long_Lines   On
              Refresh_Interval  10

        filter-kubernetes.conf: |
          [FILTER]
              Name record_modifier
              Match *
              Record cluster_name ${CLUSTER_NAME}

          [FILTER]
              Name           kubernetes
              Match          kube.*
              Kube_URL       https://kubernetes.default.svc.cluster.local:443
              Merge_Log      Off

        output-newrelic.conf: |
          [OUTPUT]
              Name  newrelic
              Match *
              licenseKey ${LICENSE_KEY}
              endpoint ${ENDPOINT}

        parsers.conf: |
          # Relevant parsers retrieved from: https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf
          [PARSER]
              Name         docker
              Format       json
              Time_Key     time
              Time_Format  %Y-%m-%dT%H:%M:%S.%L
              Time_Keep    On

          [PARSER]
             Name cri
             Format regex
             Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
             Time_Key    time
             Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    

     
   



      

